/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lucia
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cap1 = new javax.swing.JButton();
        cap2 = new javax.swing.JButton();
        cap3 = new javax.swing.JButton();
        cap4 = new javax.swing.JButton();
        cap5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(50, 51, 96));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 10, 54), 5));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 204, 255));
        jLabel1.setText("Western Moon");

        cap1.setBackground(new java.awt.Color(130, 130, 255));
        cap1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cap1.setForeground(new java.awt.Color(255, 255, 255));
        cap1.setText("Capítulo 1");
        cap1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 7));
        cap1.setDefaultCapable(false);
        cap1.setFocusable(false);
        cap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cap1ActionPerformed(evt);
            }
        });

        cap2.setBackground(new java.awt.Color(130, 130, 255));
        cap2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cap2.setForeground(new java.awt.Color(255, 255, 255));
        cap2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 7));
        cap2.setDefaultCapable(false);
        cap2.setFocusable(false);
        cap2.setLabel("Capítulo 2");
        cap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cap2ActionPerformed(evt);
            }
        });

        cap3.setBackground(new java.awt.Color(130, 130, 255));
        cap3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cap3.setForeground(new java.awt.Color(255, 255, 255));
        cap3.setActionCommand("Capítulo 3");
        cap3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 7));
        cap3.setDefaultCapable(false);
        cap3.setFocusable(false);
        cap3.setLabel("Capítulo 3");
        cap3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cap3ActionPerformed(evt);
            }
        });

        cap4.setBackground(new java.awt.Color(130, 130, 255));
        cap4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cap4.setForeground(new java.awt.Color(255, 255, 255));
        cap4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 7));
        cap4.setDefaultCapable(false);
        cap4.setFocusable(false);
        cap4.setLabel("Capítulo 4");
        cap4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cap4ActionPerformed(evt);
            }
        });

        cap5.setBackground(new java.awt.Color(130, 130, 255));
        cap5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cap5.setForeground(new java.awt.Color(255, 255, 255));
        cap5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 7));
        cap5.setDefaultCapable(false);
        cap5.setFocusable(false);
        cap5.setLabel("Capítulo 5");
        cap5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cap5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cap1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cap2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cap3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cap4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(143, 143, 143))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(cap5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cap2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cap1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cap5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cap3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cap4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cap3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cap3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cap3ActionPerformed

    private void cap4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cap4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cap4ActionPerformed

    private void cap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cap2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cap2ActionPerformed

    private void cap5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cap5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cap5ActionPerformed

    private void cap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cap1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cap1;
    private javax.swing.JButton cap2;
    private javax.swing.JButton cap3;
    private javax.swing.JButton cap4;
    private javax.swing.JButton cap5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
